export const LOGIN_WITH_GOOGLE_SUCCESS = 'LOGIN_WITH_GOOGLE_SUCCESS';
export const LOGIN_WITH_GOOGLE_FAIL = 'LOGIN_WITH_GOOGLE_FAIL';
export const GET_CURRENT_SIGNED_IN_USER_SUCCESS = 'GET_CURRENT_SIGNED_IN_USER_SUCCESS';
export const GET_CURRENT_SIGNED_IN_USER_FAIL = 'GET_CURRENT_SIGNED_IN_USER_FAIL';
export const ARE_THERE_PROJECT_TRUE = 'ARE_THERE_PROJECT_TRUE';
export const ARE_THERE_PROJECT_FALSE = 'ARE_THERE_PROJECT_FALSE';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAIL = 'GET_PROJECTS_FAIL';

